/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana13;

/**
 *
 * @author chris
 */
public class eje01 extends javax.swing.JFrame {

    /**
     * Creates new form eje01
     */
    public eje01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        txta = new javax.swing.JTextField();
        txtb = new javax.swing.JTextField();
        lbnumero1 = new javax.swing.JLabel();
        lbnumero2 = new javax.swing.JLabel();
        lbRespSuma = new javax.swing.JLabel();
        btnsumar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, -1));
        getContentPane().add(txtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 70, -1));

        lbnumero1.setText("Número 1:");
        getContentPane().add(lbnumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lbnumero2.setText("Número 2:");
        getContentPane().add(lbnumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        lbRespSuma.setText("=0");
        getContentPane().add(lbRespSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        btnsumar.setText("SUMAR");
        btnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(txta.getText());
        int b=Integer.parseInt(txtb.getText());
        lbRespSuma.setText("="+(a+b));
    }//GEN-LAST:event_btnsumarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        txta.setText("");
        txtb.setText("");
        lbRespSuma.setText("=0");
        txta.requestFocus();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsumar;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbRespSuma;
    private javax.swing.JLabel lbnumero1;
    private javax.swing.JLabel lbnumero2;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    // End of variables declaration//GEN-END:variables
}
